In [9]:
import pandas as pd
import ast

In [ ]:
df_productos = pd.read_csv("../data/ids_cervezas_enriquecidos_V2.csv")

In [20]:
df_productos.head()

,name,description,region,imageUrl,brand,specs,category,upc,ean,ean8,id_producto,categoryPath,ingredients
0,Seat Cinturón Seguridad Delantero Versa 2015 2...,Horquilla Izquierda completamente original sem...,USA or Canada,https://go-upc.s3.amazonaws.com/images/2321153...,Seat,[],NaN,NaN,NaN,1111118.0,1111118,NaN,NaN
1,Miller Genuine Draft Botella,No description found.,USA or Canada,https://go-upc.s3.amazonaws.com/images/2120112...,Miller,[],NaN,NaN,NaN,3456217.0,3456217,NaN,NaN
2,Sol Cerveza,Gezond bier dat niet te veel koolzuur bevat. M...,Unknown,https://go-upc.s3.amazonaws.com/images/1030169...,Sol,[],Beer,NaN,NaN,75001629.0,75001629,"['Food, Beverages & Tobacco', 'Beverages', 'Al...","{'text': 'Water, Barley Malt, High Maltose Syr..."
3,Corona Extra Cerveza Botella 355 Ml,"Is famous around the world for its smooth, ref...",Unknown,https://go-upc.s3.amazonaws.com/images/2013139...,Corona,"[['Size', '355 Ml'], ['Country of Origin', 'Me...",Beer,NaN,NaN,75032715.0,75032715,"['Food, Beverages & Tobacco', 'Beverages', 'Al...","{'text': '5 Ingredients Water, Barley Malt, Co..."
4,Ortuzar Cerveza Golden 473 Ml,Disfrutá la Cerveza Ortuzar Golden 473ml Elegí...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1664665...,Ortuzar,[],Beer,6.567508e+11,6.567508e+11,NaN,656750817315,"['Food, Beverages & Tobacco', 'Beverages', 'Al...",NaN

In [29]:
df_productos_v1 = pd.read_csv("../data/ids_cervezas_enriquecidos_V1.csv")

In [44]:
df_productos_v1.head()

,id_producto,productos_descripcion,barcode_formats,mpn,model,asin,title,category,manufacturer,brand,...,width,height,weight,release_date,description,features,images,last_update,stores,reviews
0,1111118,KONIGSBACHER CERVEZA ALEMANA DE TRIGO,EAN-8 01111118,TRB-9HS-CS-S,22010,B00949CTQQ,Arroyo Craftsman Timber Ridge 13 Inch Tall 1 L...,NaN,Capitol Lighting,Capitol Lighting,...,1.5748 in,5.5118 in,0.24912235606 lb,NaN,Timber Ridge 13 Inch Tall 1 Light Outdoor Wall...,['GENTLE NON-ABRASIVE LEAVE-ON EXFOLIATOR: wit...,['https://images.barcodelookup.com/32715/32715...,2024-06-23 20:03:49,[],[]
1,3456217,Cerveza MILLER Genuine Draft 330CC BOT-0.33-lt.,EAN-8 03456217,PC-100,NaN,B079H53D2B,Genuine Draft,"Food, Beverages & Tobacco","JB7, LLC",Miller,...,2.4 in,2.4 in,90 g,NaN,"Genuine Draft. Labels: Kosher, No additives, O...",['60 Billion Cfus Max Strength: Our probiotic ...,['https://images.barcodelookup.com/29822/29822...,2024-06-23 17:52:32,[],[]
2,75001629,cerveza SOL Rubia 330cc BOT-330-cc.,EAN-8 75001629,43687,43687,B07GN2H5BS,Sol,"Food, Beverages & Tobacco","Duracell Distributing, Inc",Sol,...,1.75 in,3.5 in,NaN,2018-08-16,Sol. Allergens: En:gluten. Labels: Déconseillé...,"[""Lithium Coin Battery: Duracell's 1620 3V coi...",['https://images.barcodelookup.com/32405/32405...,2024-06-23 19:52:56,[],[]
3,75032715,cerveza CORONA Rubia 330cc BOT-330-cc.,EAN-8 75032715,LiCB-CR2032-10,LiCB-CR2032-10,B071D4DKTZ,Corona Extra,"Food, Beverages & Tobacco",LiCB,Corona,...,NaN,NaN,0.0661386786 lb,NaN,Corona Extra. Serving size: 355 ml. Allergens:...,['★High Quality: Tested under Strict Quality C...,['https://images.barcodelookup.com/28021/28021...,2024-06-23 16:43:16,[],[]
4,656750797167,CERVEZA BOCATOMA AMERICAN AMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
nuevo_dato = {
    'name': 'KONIGSBACHER CERVEZA ALEMANA DE TRIGO 115ML',
    'description': 'Arroyo Craftsman Timber Ridge 13 Inch Tall 1 Light Outdoor Wall Light Timber Ridge - TRB-9HS-CS-S - Rustic',
    'region': 'Outside of North America',
    'imageUrl': '',
    'brand': 'Stella Artois',
    'specs': [['Size', '115 ml'], ['Countries', 'Germany']],
    'category': 'Beer',
    'categoryPath': ['Food, Beverages & Tobacco',
                     'Beverages',
                     'Alcoholic Beverages',
                     'Beer'],
    'upc': None,
    'ean': '1111118',
    'id_producto': '1111118'
}

# Eliminar la fila con id_producto == '1111118'
df_productos = df_productos[df_productos['id_producto'] != 1111118]

# Crear DataFrame con la nueva fila
nuevo_df = pd.DataFrame([nuevo_dato])

# Asegurar que las columnas coincidan (añadir columnas faltantes si fuera necesario)
for col in df_productos.columns:
    if col not in nuevo_df.columns:
        nuevo_df[col] = None
for col in nuevo_df.columns:
    if col not in df_productos.columns:
        df_productos[col] = None

# Reordenar columnas por consistencia
nuevo_df = nuevo_df[df_productos.columns]

# Agregar la fila al DataFrame original
df_productos = pd.concat([df_productos, nuevo_df], ignore_index=True)

In [49]:
df_productos.head()

,name,description,region,imageUrl,brand,specs,category,upc,ean,ean8,id_producto,categoryPath,ingredients,specs_parsed,specs_dict
1,Miller Genuine Draft Botella,No description found.,USA or Canada,https://go-upc.s3.amazonaws.com/images/2120112...,Miller,[],NaN,NaN,NaN,3456217.0,3456217,NaN,NaN,[],{}
2,Sol Cerveza,Gezond bier dat niet te veel koolzuur bevat. M...,Unknown,https://go-upc.s3.amazonaws.com/images/1030169...,Sol,[],Beer,NaN,NaN,75001629.0,75001629,"['Food, Beverages & Tobacco', 'Beverages', 'Al...","{'text': 'Water, Barley Malt, High Maltose Syr...",[],{}
3,Corona Extra Cerveza Botella 355 Ml,"Is famous around the world for its smooth, ref...",Unknown,https://go-upc.s3.amazonaws.com/images/2013139...,Corona,"[['Size', '355 Ml'], ['Country of Origin', 'Me...",Beer,NaN,NaN,75032715.0,75032715,"['Food, Beverages & Tobacco', 'Beverages', 'Al...","{'text': '5 Ingredients Water, Barley Malt, Co...","[[Size, 355 Ml], [Country of Origin, Mexico]]","{'Size': '355 Ml', 'Country of Origin': 'Mexico'}"
4,Ortuzar Cerveza Golden 473 Ml,Disfrutá la Cerveza Ortuzar Golden 473ml Elegí...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1664665...,Ortuzar,[],Beer,656750817315.0,656750817315.0,NaN,656750817315,"['Food, Beverages & Tobacco', 'Beverages', 'Al...",NaN,[],{}
5,Ortuzar Cerveza Scottish 473 Ml,Descubrí la Cerveza Ortuzar Scottish 473ml Ele...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1253457...,Ortuzar,[],Beer,656750817322.0,656750817322.0,NaN,656750817322,"['Food, Beverages & Tobacco', 'Beverages', 'Al...",NaN,[],{}

In [50]:
# Convertir strings que parecen listas en listas reales
df_productos['specs_parsed'] = df_productos['specs'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith('[[') else [])

# Convertir cada lista de pares en un diccionario
df_productos['specs_dict'] = df_productos['specs_parsed'].apply(lambda x: dict(x) if isinstance(x, list) else {})

# Expandir en columnas
df_specs_expandido = pd.json_normalize(df_productos['specs_dict'])

# Combinar con el dataframe original
df_final = pd.concat([df_productos, df_specs_expandido], axis=1)

In [51]:
df_final.head()

,name,description,region,imageUrl,brand,specs,category,upc,ean,ean8,...,Style,Length,Product Group,Model Number,Width,Binding,Part Number,Manufacturer,Height,Number Of Items
1,Miller Genuine Draft Botella,No description found.,USA or Canada,https://go-upc.s3.amazonaws.com/images/2120112...,Miller,[],NaN,NaN,NaN,3456217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sol Cerveza,Gezond bier dat niet te veel koolzuur bevat. M...,Unknown,https://go-upc.s3.amazonaws.com/images/1030169...,Sol,[],Beer,NaN,NaN,75001629.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Corona Extra Cerveza Botella 355 Ml,"Is famous around the world for its smooth, ref...",Unknown,https://go-upc.s3.amazonaws.com/images/2013139...,Corona,"[['Size', '355 Ml'], ['Country of Origin', 'Me...",Beer,NaN,NaN,75032715.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ortuzar Cerveza Golden 473 Ml,Disfrutá la Cerveza Ortuzar Golden 473ml Elegí...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1664665...,Ortuzar,[],Beer,656750817315.0,656750817315.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Ortuzar Cerveza Scottish 473 Ml,Descubrí la Cerveza Ortuzar Scottish 473ml Ele...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1253457...,Ortuzar,[],Beer,656750817322.0,656750817322.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df_final['name'].value_counts()

name
Stella Artois Cerveza 975 Cc                   2
Budweiser Cerveza Música En Lata 473 Cc        2
Sol Cerveza Porron Rubia                       2
Antares Cerveza Ipa Lata 473 Cc                2
Miller Genuine Draft Botella                   1
                                              ..
Patagonia Cerveza Ipa Estelar X 473 Cc         1
Quilmes Ipa Cerveza X 1 Lt                     1
Brahma Cerveza Dorada 1 Lt                     1
Budweiser Cerveza Pack X4 Uni 710cc            1
KONIGSBACHER CERVEZA ALEMANA DE TRIGO 115ML    1
Name: count, Length: 402, dtype: int64

In [61]:
import re

# Pasar a lowercase y eliminar símbolos comunes
name_clean = df_final['name'].str.lower().str.replace(r'[^\w\s]', ' ', regex=True)

# Regex más flexible: busca algo como "473ml", "473 ml", "1lt", "6x355", etc.
patron_mejorado = r'(\d+(\.\d+)?\s?(ml|l|lt|cc|cl|cm3|cmq|c)\b)'

# Extraer el primer match
df_final['volume_raw'] = name_clean.str.extract(patron_mejorado, expand=False)[0].str.strip()

In [59]:
df_final.head()

,name,description,region,imageUrl,brand,specs,category,upc,ean,ean8,...,Length,Product Group,Model Number,Width,Binding,Part Number,Manufacturer,Height,Number Of Items,volume_raw
1,Miller Genuine Draft Botella,No description found.,USA or Canada,https://go-upc.s3.amazonaws.com/images/2120112...,Miller,[],NaN,NaN,NaN,3456217.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sol Cerveza,Gezond bier dat niet te veel koolzuur bevat. M...,Unknown,https://go-upc.s3.amazonaws.com/images/1030169...,Sol,[],Beer,NaN,NaN,75001629.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Corona Extra Cerveza Botella 355 Ml,"Is famous around the world for its smooth, ref...",Unknown,https://go-upc.s3.amazonaws.com/images/2013139...,Corona,"[['Size', '355 Ml'], ['Country of Origin', 'Me...",Beer,NaN,NaN,75032715.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355 ml
4,Ortuzar Cerveza Golden 473 Ml,Disfrutá la Cerveza Ortuzar Golden 473ml Elegí...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1664665...,Ortuzar,[],Beer,656750817315.0,656750817315.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473 ml
5,Ortuzar Cerveza Scottish 473 Ml,Descubrí la Cerveza Ortuzar Scottish 473ml Ele...,USA or Canada,https://go-upc.s3.amazonaws.com/images/1253457...,Ortuzar,[],Beer,656750817322.0,656750817322.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473 ml

In [62]:
df_final['volume_raw'].value_counts()

volume_raw
473 cc     100
473 ml      42
473ml       30
473cc       25
710 cc      13
1 lt        13
1 l         12
1l          11
330 cc      11
1lt          9
500 ml       9
330ml        7
975 cc       6
500 cc       6
355 cc       5
730 ml       5
330 ml       4
355ml        3
2838ml       3
710 ml       3
740ml        3
340 cc       2
1000 cc      2
473c         2
500ml        2
730 cc       2
300 ml       2
473 cmq      1
330cc        1
800 cc       1
355cc        1
300ml        1
470cc        1
355 ml       1
530 ml       1
320 ml       1
400 ml       1
285ml        1
473 lt       1
5l           1
50 cl        1
500cc        1
925 ml       1
710cc        1
630ml        1
980 ml       1
335 cc       1
600 ml       1
473 cm3      1
730cc        1
2840ml       1
710ml        1
2838cmq      1
1892 ml      1
410 ml       1
410 cc       1
340ml        1
420 cc       1
250 ml       1
115ml        1
Name: count, dtype: int64

In [65]:
def convertir_a_ml(valor):
    if pd.isna(valor):
        return None
    valor = valor.replace(',', '.').replace(' ', '')
    try:
        if valor.endswith(('ml', 'c', 'cm3', 'cmq', 'cc')):
            return float(re.sub(r'[^\d\.]', '', valor))
        elif valor.endswith(('cl',)):
            return float(valor.replace('cl', '')) * 10
        elif valor.endswith(('lt', 'l')):
            return float(re.sub(r'[^\d\.]', '', valor)) * 1000
        else:
            return None
    except:
        return None

df_final['volume_ml'] = df_final['volume_raw'].apply(convertir_a_ml)

In [72]:
df_final['volume_ml'].value_counts()

volume_ml
473.0       200
1000.0       47
330.0        23
500.0        19
710.0        18
355.0        10
730.0         8
975.0         6
2838.0        4
740.0         3
340.0         3
300.0         3
410.0         2
925.0         1
285.0         1
473000.0      1
400.0         1
5000.0        1
320.0         1
530.0         1
470.0         1
800.0         1
4733.0        1
630.0         1
980.0         1
335.0         1
600.0         1
2840.0        1
1892.0        1
420.0         1
250.0         1
115.0         1
Name: count, dtype: int64

In [69]:
data = pd.read_csv("../data/ids_cervezas_unicos.csv", sep='|')

In [70]:
df_final.columns

Index(['name', 'description', 'region', 'imageUrl', 'brand', 'specs',
       'category', 'upc', 'ean', 'ean8', 'id_producto', 'categoryPath',
       'ingredients', 'specs_parsed', 'specs_dict', 'Size',
       'Country of Origin', 'Countries', 'Stores', 'Alcohol %', 'Weight',
       'Color', 'Unit Size & Type', 'Vintage', 'Style', 'Length',
       'Product Group', 'Model Number', 'Width', 'Binding', 'Part Number',
       'Manufacturer', 'Height', 'Number Of Items', 'volume_raw', 'volume_ml'],
      dtype='object')

In [73]:
data = data.merge(df_final[['id_producto','name', 'description', 'brand', 'specs', 'category', 'ingredients', 'specs_parsed', 'specs_dict', 'Size', 'Country of Origin', 'Countries', 'Stores', 'Alcohol %', 'Weight', 
                            'Color', 'Unit Size & Type', 'Vintage', 'Style', 'Length', 'Product Group', 'Model Number', 'Width', 'Binding', 'Part Number', 'Manufacturer', 'Height', 'Number Of Items', 'volume_raw', 'volume_ml']],
                              on='id_producto', how='left')

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 464 entries, 0 to 463
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_producto            464 non-null    object
 1   productos_descripcion  464 non-null    object
 2   name                   405 non-null    object
 3   description            405 non-null    object
 4   brand                  367 non-null    object
 5   specs                  405 non-null    object
 6   category               370 non-null    object
 7   ingredients            23 non-null     object
 8   specs_parsed           405 non-null    object
 9   specs_dict             405 non-null    object
 10  Size                   86 non-null     object
 11  Country of Origin      3 non-null      object
 12  Countries              125 non-null    object
 13  Stores                 5 non-null      object
 14  Alcohol %              1 non-null      object
 15  Weight                 2 non-null      object
 16  Color                  1 non-null      object
 17  Unit Size & Type       1 non-null      object
 18  Vintage                1 non-null      object
 19  Style                  1 non-null      object
 20  Length                 1 non-null      object
 21  Product Group          1 non-null      object
 22  Model Number           1 non-null      object
 23  Width                  1 non-null      object
 24  Binding                1 non-null      object
 25  Part Number            1 non-null      object
 26  Manufacturer           1 non-null      object
 27  Height                 1 non-null      object
 28  Number Of Items        1 non-null      object
 29  volume_raw             364 non-null    object
 30  volume_ml              364 non-null    float64
dtypes: float64(1), object(30)
memory usage: 112.5+ KB

In [76]:
data.to_csv("../data/ids_cervezas_enriquecidos.csv", index=False)